export const sampleQuestions = [
  {
    question_id: "347",
    question_text: "south",
    question_image: "",
    question_answers: "",
    question_valid_answer: "south",
    course_id: "9",
    unit_id: "22",
    video_id: null,
    type: "arrangePuzzle",
    gameType: "character",
    hint: "جنوب",
    correctSentence: "south",
    str_shuffle: [
      "o",
      "t",
      "u",
      "s",
      "h"
    ],
    real_answers: []
  },
  {
    question_id: '3184',
    question_text: 'He was _________ when his team won. ',
    question_image: '',
    question_answers: ['happy', 'nervous', 'sad'],
    question_valid_answer: 'happy',
    course_id: '8',
    unit_id: '41',
    video_id: null,
    type: 'mcq',
    gameType: 'character',
    hint: '',
    real_answers: [
      {answer_text: 'happy', answer_exp: '', answer_check: true},
      {answer_text: 'nervous', answer_exp: '', answer_check: false},
      {answer_text: 'sad', answer_exp: '', answer_check: false},
    ],
  },
  {
    question_id: '3185',
    question_text: 'Salma was _________ before her exam.',
    question_image: '',
    question_answers: ['excited', 'worried', 'happy'],
    question_valid_answer: 'worried',
    course_id: '8',
    unit_id: '41',
    video_id: null,
    type: 'mcq',
    gameType: 'character',
    hint: '',
    real_answers: [
      {answer_text: 'excited', answer_exp: '', answer_check: false},
      {answer_text: 'worried', answer_exp: '', answer_check: true},
      {answer_text: 'happy', answer_exp: '', answer_check: false},
    ],
  },
  {
    question_id: '3186',
    question_text: 'Ahmed _________ proud after scoring a goal. ',
    question_image: '',
    question_answers: ['hurt', 'went', 'felt'],
    question_valid_answer: 'felt',
    course_id: '8',
    unit_id: '41',
    video_id: null,
    type: 'mcq',
    gameType: 'character',
    hint: '',
    real_answers: [
      {answer_text: 'hurt', answer_exp: '', answer_check: false},
      {answer_text: 'went', answer_exp: '', answer_check: false},
      {answer_text: 'felt', answer_exp: '', answer_check: true},
    ],
  },
  {
    question_id: '3187',
    question_text: 'My brother _________ a goal.',
    question_image: '',
    question_answers: ['started', 'felt', 'scored'],
    question_valid_answer: 'scored',
    course_id: '8',
    unit_id: '41',
    video_id: null,
    type: 'mcq',
    gameType: 'character',
    hint: '',
    real_answers: [
      {answer_text: 'started', answer_exp: '', answer_check: false},
      {answer_text: 'felt', answer_exp: '', answer_check: false},
      {answer_text: 'scored', answer_exp: '', answer_check: true},
    ],
  },
  {
    question_id: '3188',
    question_text: 'He was worried about making _________.',
    question_image: '',
    question_answers: ['mistakes', 'games', 'goals'],
    question_valid_answer: 'mistakes',
    course_id: '8',
    unit_id: '41',
    video_id: null,
    type: 'mcq',
    gameType: 'character',
    hint: '',
    real_answers: [
      {answer_text: 'mistakes', answer_exp: '', answer_check: true},
      {answer_text: 'games', answer_exp: '', answer_check: false},
      {answer_text: 'goals', answer_exp: '', answer_check: false},
    ],
  },
  {
    question_id: '3189',
    question_text: 'He _________ proud after scoring a goal. ',
    question_image: '',
    question_answers: ['felt', 'fell', 'feel'],
    question_valid_answer: 'felt',
    course_id: '8',
    unit_id: '41',
    video_id: null,
    type: 'mcq',
    gameType: 'character',
    hint: '',
    real_answers: [
      {answer_text: 'felt', answer_exp: '', answer_check: true},
      {answer_text: 'fell', answer_exp: '', answer_check: false},
      {answer_text: 'feel', answer_exp: '', answer_check: false},
    ],
  },
  {
    question_id: '3190',
    question_text: 'He was _________ when his team won the game. ',
    question_image: '',
    question_answers: ['sad', 'happy', 'tired'],
    question_valid_answer: 'happy',
    course_id: '8',
    unit_id: '41',
    video_id: null,
    type: 'mcq',
    gameType: 'character',
    hint: '',
    real_answers: [
      {answer_text: 'sad', answer_exp: '', answer_check: false},
      {answer_text: 'happy', answer_exp: '', answer_check: true},
      {answer_text: 'tired', answer_exp: '', answer_check: false},
    ],
  },
  {
    question_id: '3191',
    question_text: 'It was my first football _________. ',
    question_image: '',
    question_answers: ['match', 'number', 'name'],
    question_valid_answer: 'match',
    course_id: '8',
    unit_id: '41',
    video_id: null,
    type: 'mcq',
    gameType: 'character',
    hint: '',
    real_answers: [
      {answer_text: 'match', answer_exp: '', answer_check: true},
      {answer_text: 'number', answer_exp: '', answer_check: false},
      {answer_text: 'name', answer_exp: '', answer_check: false},
    ],
  },
  {
    question_id: '3192',
    question_text: 'My team _________ the game yesterday. ',
    question_image: '',
    question_answers: ['wins', 'win', 'won'],
    question_valid_answer: 'won',
    course_id: '8',
    unit_id: '41',
    video_id: null,
    type: 'mcq',
    gameType: 'character',
    hint: '',
    real_answers: [
      {answer_text: 'wins', answer_exp: '', answer_check: false},
      {answer_text: 'win', answer_exp: '', answer_check: false},
      {answer_text: 'won', answer_exp: '', answer_check: true},
    ],
  },
  {
    question_id: '3193',
    question_text: "Eman was worried, _________ she didn't stop.",
    question_image: '',
    question_answers: ['after', 'and', 'but'],
    question_valid_answer: 'but',
    course_id: '8',
    unit_id: '41',
    video_id: null,
    type: 'mcq',
    gameType: 'character',
    hint: '',
    real_answers: [
      {answer_text: 'after', answer_exp: '', answer_check: false},
      {answer_text: 'and', answer_exp: '', answer_check: false},
      {answer_text: 'but', answer_exp: '', answer_check: true},
    ],
  },
  {
    question_id: '3194',
    question_text: 'We _________ football in the park yesterday. ',
    question_image: '',
    question_answers: ['played', 'play', 'plays'],
    question_valid_answer: 'played',
    course_id: '8',
    unit_id: '41',
    video_id: null,
    type: 'mcq',
    gameType: 'character',
    hint: '',
    real_answers: [
      {answer_text: 'played', answer_exp: '', answer_check: true},
      {answer_text: 'play', answer_exp: '', answer_check: false},
      {answer_text: 'plays', answer_exp: '', answer_check: false},
    ],
  },
  {
    question_id: '3195',
    question_text: 'I felt proud of myself.',
    question_image: '',
    question_answers: '',
    question_valid_answer: 'I felt proud of myself.',
    course_id: '8',
    unit_id: '41',
    video_id: null,
    type: 'arrangePuzzle',
    gameType: 'word',
    hint: '',
    correctSentence: 'I felt proud of myself.',
    str_shuffle: ['of', 'myself.', 'felt', 'I', 'proud'],
    real_answers: [],
  },
  {
    question_id: '3196',
    question_text: 'My team won the game.',
    question_image: '',
    question_answers: '',
    question_valid_answer: 'My team won the game.',
    course_id: '8',
    unit_id: '41',
    video_id: null,
    type: 'arrangePuzzle',
    gameType: 'word',
    hint: '',
    correctSentence: 'My team won the game.',
    str_shuffle: ['My', 'team', 'the', 'won', 'game.'],
    real_answers: [],
  },
  {
    question_id: '3197',
    question_text: 'She watched a football match.',
    question_image: '',
    question_answers: '',
    question_valid_answer: 'She watched a football match.',
    course_id: '8',
    unit_id: '41',
    video_id: null,
    type: 'arrangePuzzle',
    gameType: 'word',
    hint: '',
    correctSentence: 'She watched a football match.',
    str_shuffle: ['watched', 'She', 'a', 'football', 'match.'],
    real_answers: [],
  },
  {
    question_id: '3198',
    question_text: 'I was tired and nervous.',
    question_image: '',
    question_answers: '',
    question_valid_answer: 'I was tired and nervous.',
    course_id: '8',
    unit_id: '41',
    video_id: null,
    type: 'arrangePuzzle',
    gameType: 'word',
    hint: '',
    correctSentence: 'I was tired and nervous.',
    str_shuffle: ['was', 'tired', 'I', 'nervous.', 'and'],
    real_answers: [],
  },
  {
    question_id: '3199',
    question_text: 'Ola was worried about making mistakes.',
    question_image: '',
    question_answers: '',
    question_valid_answer: 'Ola was worried about making mistakes.',
    course_id: '8',
    unit_id: '41',
    video_id: null,
    type: 'arrangePuzzle',
    gameType: 'word',
    hint: '',
    correctSentence: 'Ola was worried about making mistakes.',
    str_shuffle: ['worried', 'Ola', 'making', 'was', 'about', 'mistakes.'],
    real_answers: [],
  },
  {
    question_id: '3200',
    question_text: 'We played a football match.',
    question_image: '',
    question_answers: '',
    question_valid_answer: 'We played a football match.',
    course_id: '8',
    unit_id: '41',
    video_id: null,
    type: 'arrangePuzzle',
    gameType: 'word',
    hint: '',
    correctSentence: 'We played a football match.',
    str_shuffle: ['played', 'football', 'match.', 'We', 'a'],
    real_answers: [],
  },
];

