import Home from './HomeScreen';
import Courses from './Courses';
import Exams from './Exams';
import QuestionBank from './Questionbank';
import Profile from './Profile';
import CoursePlayer from './CoursePlayer';
import ExamQuestion from './ExamQuestions';
import ExamResults from './ExamResults';
import QuestionStages from './QuestionStages';
import VidPlayer from './VidPlayer';
export {Home, Courses, Exams, QuestionBank, Profile, CoursePlayer, ExamResults, QuestionStages, VidPlayer};
